### ISSUE TITLE
仓库名字是esp8266芯片。但是阿里智能的乐鑫款的芯片仅仅支持 esp-wroom-02！

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp8266-alink-v1.0#1]
仓库名字是esp8266芯片。但是阿里智能的乐鑫款的芯片仅仅支持 esp-wroom-02！

**Comment by allanchen24** [comment]
esp-wroom-02 是模块名字，该模块使用的就是 esp8266 芯片，在阿里智能后台新建设备时选择 esp-wroom-02 即可。
