### ISSUE TITLE
所有功能都正常了，但是远程升级不了!

### ISSUE THREAD

**Issue by deny2010** [espressif/esp8266-alink-v1.0#8]
log信息看，已经收到升级命令了，但是提示参数错误，请问该怎么处理。
<ALINK/DEBUG> [process_received_buf#295]: message type 1 length 144
<ALINK/DEBUG> [process_msg_response#89]: TEST: receive response msgid=55
<ALINK/DEBUG> [wsf_msg_queue_push#58]: req_queue->length 1
<ALINK/DEBUG> [send_worker#766]: get response msg id:55
<ALINK/DEBUG> [wsf_invoke#116]: ----------- end wait for invoke session   -----------
<ALINK/DEBUG> [send_worker#712]: send_worker waiting on queue 3fff25b8
<ALINK/DEBUG> [wsf_invoke#128]: result code 0
<ALINK/DEBUG> [wsf_invoke#152]: wsf_msg_session_destroy
<ALINK/DEBUG> [alink_response_get_code#644]: [{"result":{"code":1000,"msg":"success"},"id":12}]
<ALINK/DEBUG> [alink_post#1037]: alink_response_get_code: success wait time:1 ms
alink_ota_status_post: {"version":"1.1.1","step":"0","stepPercent":"100"}, ret=1000
D alink_param: [alink_read_flash_config, 57]:read config[0m
step:ALINK_OTA_DOWNLOAD !
[0;31mE alink_ota: [esp_ota_firmware_save, 39]:Parameter error: !buffer[0m
state: 5 -> 0 (0)
rm 0
pm close 7 0 0/28043496
del if0
usl
sul 0 0

**Comment by xiongyumail** [comment]
@deng2010 
在`esp_ota_firmware_save` 打印下buffer ?

**Comment by deny2010** [comment]
![image](https://user-images.githubusercontent.com/32917979/56330759-1d9bb380-61bc-11e9-86aa-59e391c53adb.png)

**Comment by xiongyumail** [comment]
@deny2010 
把这两个检查注释掉吧，alink库传递过来的第一个`buffer`是个空指针, 麻烦试下。
```
int esp_ota_firmware_save(char * buffer, int len)
{
    //ALINK_PARAM_CHECK(!buffer);
    //ALINK_PARAM_CHECK(len < 0);
    
    ALINK_LOGI("start firmware update");
    return upgrade_download(buffer, len);
}
```

**Comment by deny2010** [comment]
你好！我已经安装上面说的注释掉，就可以升级，但是升级成功率很低，或者升级时间超长，最快也要4-5分钟，最慢的就长达10分钟以上，或者超时失败。请问这个问题怎么优化。

**Comment by deny2010** [comment]
这个可以排除WIFI信号弱问题，路由器就在旁边！

**Comment by deny2010** [comment]
根据检测串口升级数据，有时候1-2分钟才打印一串这样升级字符出来。
![image](https://user-images.githubusercontent.com/32917979/57023074-af4afc80-6c63-11e9-9e85-88a31c7d15df.png)

**Comment by deny2010** [comment]
![image](https://user-images.githubusercontent.com/32917979/57023097-b96cfb00-6c63-11e9-959f-9e66702ed3a3.png)

**Comment by xiongyumail** [comment]
@deny2010 
在<https://github.com/espressif/esp8266-alink-v1.0/blob/master/esp8266-rtos-sdk/include/lwip/lwipopts.h>里

把`#define TCP_QUEUE_OOSEQ                 0`
设置为`#define TCP_QUEUE_OOSEQ                 1`

然后再到<https://github.com/espressif/esp8266-alink-v1.0/tree/master/esp8266-rtos-sdk/third_party>下重新编译lwip
`./make_lib.sh lwip`

**Comment by deny2010** [comment]
好的，谢谢，问题已经解决！
